
#datasource

spring:
  datasource:
    url: jdbc.mysql:///sprintboot?UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver


#mybatis
mybatis:
  mapper-locations: classpath:mapper/*mapper.xml  #mapper映射文件路径,匹配所有以mapper.xml结尾的文件
  type-aliases-package: com.yunxiao.frame.entity  #实体类的包地址,这是用于起别名的
# check-config-location:  指定mybatis的核心配置文件



